
-- 更新名字 --
UPDATE GLP_COUNTRY_STATE SET `NAME`=ABBREVIATION WHERE COUNTRY_ID=45;
-- 去掉台湾、香港、澳门 --
DELETE FROM GLP_COUNTRY_STATE WHERE COUNTRY_ID=45 AND ID IN(202, 203, 204);
-- country表增加是否国家地区、排序字段 --
ALTER TABLE GLP_COUNTRY ADD COLUMN IS_COUNTRY VARCHAR(1) NOT NULL DEFAULT '1';
ALTER TABLE GLP_COUNTRY ADD COLUMN IS_HAVE_CITY VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '1,有城市;0,无城市';
-- 新增 --
UPDATE GLP_COUNTRY SET IS_COUNTRY='0' WHERE ID IN(96, 125,208);
UPDATE GLP_COUNTRY SET `NAME`='Macau(CN)' WHERE ID=125;
UPDATE GLP_COUNTRY SET `NAME`='Hong Kong(CN)' WHERE ID=96;
UPDATE GLP_COUNTRY SET `IS_HAVE_CITY`='0' WHERE ID IN(96, 125);




-- update role id --
UPDATE GLP_BUSINESS SET ROLE_ID='1' WHERE ROLE_ID='5';
-- 新增2个字段 --
ALTER TABLE GLP_BUSINESS MODIFY COLUMN ROLE_ID VARCHAR(50) NOT NULL, MODIFY COLUMN INTERNAL_ROLE_ID VARCHAR(50) NULL, ADD COLUMN ROLE_NAME VARCHAR(255) NOT NULL DEFAULT '', ADD COLUMN INTERNAL_ROLE_NAME VARCHAR(255) NULL;
ALTER TABLE GLP_BUSINESS_REFERENCE MODIFY COLUMN ROLE_ID VARCHAR(50) NOT NULL, ADD COLUMN ROLE_NAME VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE GLP_REFER_BUSINESS MODIFY COLUMN ROLE_ID VARCHAR(50) NOT NULL, ADD COLUMN ROLE_NAME VARCHAR(255) NOT NULL DEFAULT '';


-- 更新名称 --
UPDATE GLP_BUSINESS t, GLP_COMMON_DATA t1 SET t.ROLE_NAME=t1.`NAME` WHERE t.`ROLE_ID`=t1.`ID` AND t1.`TYPE_ID`='5';
UPDATE GLP_BUSINESS t, GLP_COMMON_DATA t1 SET t.INTERNAL_ROLE_NAME=t1.`NAME` WHERE t.`INTERNAL_ROLE_ID`=t1.`ID` AND t1.`TYPE_ID`='3';


-- 新增Business_Role --

ALTER TABLE `glp`.`GLP_COMMON_DATA` DROP PRIMARY KEY;
CREATE UNIQUE INDEX UNI_COMMON_DATA ON GLP_COMMON_DATA(ID,PARENT_ID,TYPE_ID);
-- add business role id to common data type --
INSERT INTO GLP_COMMON_DATA_TYPE(ID, `NAME`)VALUES(5, 'business role id');
-- add business role to common_data --
INSERT INTO GLP_COMMON_DATA(ID, `NAME`, PARENT_ID, IORDER, TYPE_ID)
VALUES('1', 'Manufacturers', NULL, 1, '5'),
('3', 'Distributors', NULL, 2, '5'),
('2', 'Wholesalers', NULL, 3, '5'),
('4', 'Retailers', NULL, 4, '5'),
('0101', 'Producers', '1', 1, '5'),
('0102', 'Brand Owners', '1', 2, '5'),
('0301', 'National Distributors', '3', 1, '5'),
('0302', 'State/Provincial Distributors', '3', 2, '5'),
('0401', 'Department Stores', '4', 1, '5'),
('0402', 'Supermarkets', '4', 2, '5'),
('0403', 'Warehouse Retailers', '4', 3, '5'),
('0404', 'Specialty Retailers', '4', 4, '5'),
('0405', 'E-tailers', '4', 5, '5'),
('0406', 'Convenience Retailers', '4', 6, '5'),
('0407', 'Discount Retailers', '4', 7, '5'),
('0408', 'Franchisees', '4', 8, '5'),
('0409', 'Body Shops', '4', 9, '5'),
('0410', 'Others', '4', 10, '5');

-- modify internal business role --
INSERT INTO GLP_COMMON_DATA(ID, `NAME`, PARENT_ID, IORDER, TYPE_ID)
VALUES('0301', 'Regular Chain Stores', '3', 1, '3'),
('0302', 'Voluntary Chain Stores', '3', 2, '3');

DELETE FROM GLP_COMMON_DATA WHERE ID='4' AND TYPE_ID='3';
UPDATE GLP_COMMON_DATA SET `NAME`='Chain Store' WHERE ID='3' AND TYPE_ID='3';
UPDATE GLP_COMMON_DATA SET `NAME`='Headquarters' WHERE ID='1' AND TYPE_ID='3';
UPDATE GLP_COMMON_DATA SET `NAME`='Branches' WHERE ID='2' AND TYPE_ID='3';
UPDATE GLP_COMMON_DATA SET `NAME`='Chain Stores' WHERE ID='3' AND TYPE_ID='3';
UPDATE GLP_COMMON_DATA SET `NAME`='Others' WHERE ID='900000' AND TYPE_ID='3';


UPDATE GLP_BUSINESS SET INTERNAL_ROLE_ID='3-0301', INTERNAL_ROLE_NAME='Chain Stores->Regular Chain Stores' WHERE INTERNAL_ROLE_ID='3';
UPDATE GLP_BUSINESS SET INTERNAL_ROLE_ID='3-0302', INTERNAL_ROLE_NAME='Chain Stores->Voluntary Chain Stores' WHERE INTERNAL_ROLE_ID='4';
UPDATE GLP_BUSINESS t, GLP_COMMON_DATA t1 SET t.ROLE_NAME=t1.NAME WHERE t.ROLE_ID=t1.ID AND t1.TYPE_ID='5';









